#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
if (file_exists($composerAutoload = __DIR__.'/vendor/autoload.php')) {
    require $composerAutoload;
}

// Ensure the application can be configured...
$app = require_once __DIR__.'/bootstrap/app.php';

// Handle the incoming command...
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
